#!/bin/bash
dirname=${PWD##*/}
archive=${dirname/-/_}.orig.tar.gz
read -p "Create \"../${archive}\" file (y/n)?" -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    make distclean

    cd ..
    tar --exclude-vcs -zcvf ${archive} ./${dirname}
    cd "$dirname"
    echo "Done creating ../${archive}"
fi

