#!/bin/bash
read -p "Create orig.tar.gz file (y/n)?" -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    make distclean
    dirname=${PWD##*/}
    archive=${dirname/-/_}.orig.tar.gz
    cd ..
    tar --exclude-vcs -zcvf ${archive} ./${dirname}
    cd "$dirname"
    echo "Done creating ../${archive}"
fi

