#!/bin/bash
dirname=${PWD##*/}
archive=${dirname/-/_}.orig.tar.gz
read -p "Create \"../${archive}\" file (y/n)?" -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    make distclean

    cd ..
    tar --exclude='./debian' --exclude-vcs -zcvf ${archive} ./${dirname}
    cd "$dirname"
    echo "Done creating ../${archive}"
    echo
    read -p "Launch \"debuild -us -uc\" on the package now (y/n)?" -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
    	debuild -us -uc
    fi
fi

